-- MySQL Script generated by MySQL Workbench
-- Aluna: Cássia Oliveira dos Santos
-- Professor: Enéias Monteiro da Silva
-- sáb 18 dez 2021 10:11:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola_Recuperacao_CassiaSantos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola_Recuperacao_CassiaSantos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola_Recuperacao_CassiaSantos` ;
USE `escola_Recuperacao_CassiaSantos` ;

-- -----------------------------------------------------
-- Table `escola_Recuperacao_CassiaSantos`.`tabCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_Recuperacao_CassiaSantos`.`tabCurso` (
  `codigoCurso` INT(3) AUTO_INCREMENT NOT NULL,
  `descricaoCurso` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigoCurso`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `escola_Recuperacao_CassiaSantos`.`tabAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola_Recuperacao_CassiaSantos`.`tabAluno` (
  `matriculaAluno` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpfAluno` BIGINT(11) NOT NULL,
  `nomeCompletoAluno` VARCHAR(100) NOT NULL,
  `enderecoAluno` VARCHAR(150) NOT NULL,
  `dataNascAluno` DATE NOT NULL,
  `tabCurso_codigoCurso` INT(3) NOT NULL,
  PRIMARY KEY (`matriculaAluno`, `tabCurso_codigoCurso`),
  INDEX `fk_tabAluno_tabCurso_idx` (`tabCurso_codigoCurso` ASC) VISIBLE,
  CONSTRAINT `fk_tabAluno_tabCurso`
    FOREIGN KEY (`tabCurso_codigoCurso`)
    REFERENCES `escola_Recuperacao_CassiaSantos`.`tabCurso` (`codigoCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------------------------------------------------
-- TESTES:
-- ----------------------------------------------------
show tables;
select * from tabCurso;
select * from tabAluno;
/*DROP TABLE tabCurso;
DROP TABLE tabAluno;*/

-- -----------------------------------------------------
-- INSERÇÃO DE VALORES - POPULAÇÃO DA BASE DE DADOS:
-- -----------------------------------------------------
-- INSERÇÃO DE VALORES NA ENTIDADE CURSO:
insert into tabCurso(descricaoCurso) values("Graduação Semi-presencial em Análise e Desenvolvimento de Sistemas");
insert into tabCurso(descricaoCurso) values("Técnico em Administração - Presencial");
insert into tabCurso(descricaoCurso) values("Tecnólogo EAD em Sistemas para a Internet");
insert into tabCurso(descricaoCurso) values("Pós-graduação presencial de Inteligencia Artificial");
insert into tabCurso(descricaoCurso) values("Bacharelado EAD Semipresencial em Engenharia de Computação");

-- INSERÇÃO DE VALORES NA ENTIDADE ALUNO:
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (06509869503, "Ercuien Vureth Silva", "Rua das Ventos Uivantes, 17", 19850908, 1);
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (13119237051, "Jacinto Matosinhos Cangueiro", "Trav. Perto sei lá de onde, 900", '2001-09-12', 5);
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (72269514017, "Ibrahima Milheiriço Arantes", "Trav. Edivaldo Leite, 15", '2000-12-08', 4);
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (22125271044, "Izabel Carreiro Marçal Silva", "Rua Medeiros, 1000", '1988-10-15', 3);
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (17923435074, "Camilla Vilante Negrão", "Rua das Flores, 13", '2003-06-05', 2);
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (17923835073, "Camilla silveira Leal", "Rua da Felicidade, 1290", '1987-06-19', 3);
insert into tabAluno(cpfAluno, nomeCompletoAluno, enderecoAluno, dataNascAluno, tabCurso_codigoCurso) values (17929835073, "Ana Paula silveira Furtado", "Aven. Não quero pensar, 28", '1977-06-10', 4);